# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "storage/**/*"
    - "config/**/*"

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Style/Documentation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "app/controllers/**/*"
